### ISSUE TITLE
Apostrophe Not Working In Belly Input

### ISSUE THREAD

**Issue by tanya17365** [mayacakmak/robotfrontend#13]
While creating a new screen for the ACT Yes And No micro-interaction, any text including and after the apostrophe in the belly screen was not accepted and disappeared after typing it. Most other common special characters work, however.

**Comment by kaimihata** [comment]
Need to replace the quotes in the strings we are trying to render with escaped versions of the strings, so we can instead of showing `screen.instructionLarge.text` we need to instead show `screen.instructionLarge.text.replace(/'/g, '&#39;')` to replace the single quote with the HTML escaped single quote (and the same with the `instructionSmall`.
