### ISSUE TITLE
Undefined Robot

### ISSUE THREAD

**Issue by tanya17365** [mayacakmak/robotfrontend#9]
While attempting to edit the belly screens for the test robot, the frontend link reset itself or refreshed and instead showed me an empty robot. When I went back to the main screen, it did not show me the list of robots and only displayed 'undefined'.
Patricia faced the same issue when she opened the robot setup links at her end.
![Screenshot (99)](https://user-images.githubusercontent.com/44595936/87536963-83c10000-c6b7-11ea-8ce7-a336cc366428.png)

**Comment by kaimihata** [comment]
If you click on a link (Start Robot Setup, Start Robot Controller, etc) before the list of robots loads, when you navigate to clicked page the robot index will be -1. Then if you make any changes on that page (add a face, etc) it will add an entry into the database with robot index -1. Then, when the site loads the list of robots later it says undefined since there is an array with index -1.
